# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c28ec574a5917979c4b6bc4904eb40ab9c042ac884e6367566ecf43b7e3d65a68da2c45503d313cfb119be46a06ae0f0264cc66188a4b7abd9a2c68b3a652a2

test:
  secret_key_base: 1ef2e9ab3d113e1c88fdbe1138a295e36187b131049aeadfcf4429a1d4f2b2eed3f04b7f53adc7a4365144bb3a5c3e7254eb6c6a69a265e1e3b2742ad4e664db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
